services:
  - type: web
    name: server-clonecraft
    runtime: node
    rootDir: server
    buildCommand: "npm install"
    startCommand: "node index.js"
    buildpacks:
      - url: https://github.com/heroku/heroku-buildpack-google-chrome
    envVars:
      - key: GOOGLE_CHROME_BIN
        value: "/app/.apt/usr/bin/google-chrome"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true 