services:
  - type: web
    name: clonecraft-server
    env: node
    plan: starter
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
    buildFilter:
      paths:
        - server/**
    healthCheckPath: /api/test-environment 