services:
  - type: web
    name: server-clonecraft
    runtime: node
    rootDir: server
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
    buildPacks:
      - url: https://github.com/heroku/heroku-buildpack-google-chrome 