services:
  - type: web
    name: server-clonecraft
    runtime: node
    rootDir: server
    buildCommand: "npm install && npx puppeteer browsers install chrome"
    startCommand: "node index.js"
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
      - key: PUPPETEER_CACHE_DIR
        value: "/opt/render/.cache/puppeteer"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/opt/render/.cache/puppeteer/chrome-linux/chrome" 