services:
  - type: web
    name: server-clonecraft
    runtime: node
    rootDir: server
    buildCommand: "npm install"
    startCommand: "find / -name google-chrome -type f 2>/dev/null; node index.js"
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
    buildpacks:
      - url: https://github.com/heroku/heroku-buildpack-google-chrome 