services:
  - type: web
    name: server-clonecraft
    runtime: node
    rootDir: server
    buildCommand: "npm install && echo '🔍 Checking Chrome installation...' && ls -la /app/.apt/usr/bin/ | grep chrome || echo '❌ Chrome not found in expected location' && echo '🔍 Checking system Chrome...' && which google-chrome || echo '❌ System Chrome not found' && echo '🔍 Checking Puppeteer cache...' && ls -la /opt/render/.cache/puppeteer/ || echo '❌ Puppeteer cache not found'"
    startCommand: "node index.js"
    buildpacks:
      - url: https://github.com/heroku/heroku-buildpack-google-chrome
    envVars:
      - key: GOOGLE_CHROME_BIN
        value: "/app/.apt/usr/bin/google-chrome"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/app/.apt/usr/bin/google-chrome" 